spring:
  datasource:
    url: jdbc:mysql://10.36.140.140:3306/dubbo2?serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
dubbo:
  application:
    name: class
  registry:
    address: zookeeper://192.168.26.123:2181
  protocol:
    port: -1
  consumer:
    check: false
