spring:
  datasource:
    url: jdbc:mysql://118.24.246.168:3306/class?serverTimezone=GMT%2B8
    username: student
    password: student
    driver-class-name: com.mysql.cj.jdbc.Driver
dubbo:
  application:
    name: class
  registry:
    address: zookeeper://192.168.50.129:2181
  protocol:
    port: -1
  consumer:
    check: false
